name: atividadefinal
description: Projeto Flutter final
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: "^2.30.0"
  firebase_auth: "^4.17.0"
  cloud_firestore: "^4.15.0"
  firebase_storage: "^11.6.0"
  firebase_messaging: "^14.7.10"
  firebase_database: "^10.4.0"

  # Login Social
  google_sign_in: "^6.2.1"
  flutter_facebook_auth: "^6.1.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
